### PR TITLE
Some Fixes for #6

### LINKED ISSUE #6: Some small issues with polls and super-chat styling
Some things I noticed during the last stream
- [x] Usernames in super-chats from paid rumble subscribers are hard to read:
image
- [x] Same with links:
image
- [x] `!endpoll` makes the poll disappear. It should probably just stop accepting votes, mark the option that won and then maybe after a timeout of 15 seconds or so it should actually fade out
- [x] At the end of the stream the poll timed out after two minutes while you were looking for the outro song, idk if you want that changed

Fixing the readability is a bit hard since the color of the super-chat changes so the colors would have to be dependent on that.

I also saw that some users in chat couldn't figure out how to vote and used `!vote1`, `!1` or just the number. I could make the counting a bit more flexible so it accounts for really dense people who can't follow simple instructions. Someone also suggested that the messages people send for voting shouldn't show up in the chat overlay so they don't clutter it up.

Lastly something I thought about that might be useful is the web server hosting a separate dashboard page that aggregates all donations during a stream. That way you don't have to go to the different sites to read them at the end and you'll also not lose them if you refresh rumble. The dashboard could also offer some other options like starting/ending polls or re-submitting a super-chat in case it gets lost when refreshing the overlay in obs. That dashboard could also be added as dock to obs since obs studio allows you to dock any website you want via the menu bar option `Docks > Custom Browser Docks`. If that's something that you'd find useful I can try and make a basic version of it.

### PR DESCRIPTION
**Pull request by cohlexyz**
- Using `!endpoll` now highlights the winning option and then fades out after 10 seconds:
Screenshot_20231021_230633
- Polls now also accept votes in the form of `!1` or just the number `1`
- Poll votes and commands do not show up in the chat overlay anymore
- Polls no longer end automatically

I also increased the brightness of the Username color for rumble subscribers a bit to try and make them more readable in superchats.

Before:
Screenshot_20231021_233141

After:
Screenshot_20231021_232554

Closes #6

### CODE REVIEW

File: public/script.js [hunk 1]
```diff
@@ -169,17 +205,19 @@ function handle_command(message) {
...
-
-    else if (msg.startsWith("!vote")) {
-        if (active_poll === null)
-            return;
+    else if (active_poll !== null && active_poll.is_valid_vote(message.message)) {
         active_poll.handle_vote_message(message);
+        command_handled = true;
     }
+
+    return command_handled;
```
Comment (ghost) [inline public/script.js]: Could return `true` here then return `false` instead of `void` in the nested `if` statements. This eliminates the need for `command_handled` and has the benefit of a single return type.

Comment (cohlexyz) [reply public/script.js]: Yeah those `void` returns weren't on purpose, I just forgot to make them return false.

**Comment by cohlexyz** [comment]
Since you're already here, I saw you lost all the rumble super-chats today, so I thought I'd try and at least get a basic version of a dashboard going:

image

It saves the donations using browser local storage, so they'll stick around until you manually delete them with the buttons at the top. You can also re-send them to the obs overlay with the "🔄" icon.

I can make a PR for this tomorrow if you want.

**Comment by jaw-sh** [comment]
I don't need it separated by source, I'd prefer it by chronological. Maybe if there's multiple ways of viewing it that's fine.

Whatever you're doing shouldn't be stored in JS btw. It needs to be accessible from the Rust server.

**Comment by cohlexyz** [comment]
I can merge it into one list, but why would the data need to be accessible from the server? I've added the dashboard as an `/dashboard` endpoint to the server, but the page is just a static page with some javascript connecting to the websocket and parsing the incoming donations.

**Comment by jaw-sh** [comment]
Because then I can do anything I want with it and do not rely on the overlay to manage data?

**Comment by cohlexyz** [comment]
I thought of the dashboard more as just a way to keep track of the donations for a stream. Would you want the data permanently stored on the server side via sqlite or something, or just temporarily in memory? For simplicity I'd probably just go with the latter for now.

**Comment by ghost** [comment]
Some sort of stored database would probably be a nice feature for collecting a streamer's long-term financial data. I can handle moving it from memory if Jersh gives the OK.

**Comment by jaw-sh** [comment]
Rust can easily store messages in memory for the lifetime of the program. An SQLite DB would be overkill, unless you really want to. But it needs some way to delineate between streams which is a lot of work.

**Comment by ghost** [comment]
> But it needs some way to delineate between streams which is a lot of work.

I have some ideas as to how I could make this work. It doesn't seem hard to do as opposed to typical DB work, but I would rather prioritize more important things, if any.

**Comment by jaw-sh** [comment]
The \#\1 issue I have right now is that I have no access to superchats on Rumble if anything happens to the tab the userscript is on. \#\2 is that Odysee breaks because we need to switch to websocket scraping.

**Comment by ghost** [comment]
I can store fetched superchats into a vector or something to keep it independent of browser state. That doesn't seem like it would take me long to do. Ngl, I can't figure out Odysee's interface and actually find a stream to test with; maybe I'm just too dumb for alt tech.

**Comment by TheRenegadist** [comment]
I don't know nothing about no coding but I do know how to stream to Odysee, not sure your timezone but tomorrow when I get off work if you need a stream to use as a guinea pig I'd be happy to offer myself up. I get home around 3:30PM PDT Commiefornia time, if you need the help let me know and I'll go live.

**Comment by cohlexyz** [comment]
> I can store fetched superchats into a vector or something to keep it independent of browser state. That doesn't seem like it would take me long to do.

If you add an endpoint where the dashboard can fetch the stored superchats I can switch from using browser storage to that.
